title: hermes.log
email: dovydasgulbinas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lets Make Things Run Themselves
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: Home-AssistantConfig # the GitHub repo name for your project
github_username: megamorphf

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: megamorphf

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

collections:
  jokes:
    output: true

# plugins:
  # - jekyll-feed
  # - jemoji
  # - jekyll-auto-image


img: "/assets/img/"
git_domain: "https://www.megamorphf.github.io"


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

  - scope:
      path: ""
      type: jokes
    values:
      layout: page
