title: "dovydas.log"
email: dovydas.gulbinas@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let Us Make Things Run Themselves
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dovydasgulbinas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: Home-AssistantConfig # the GitHub repo name for your project
github_username: dovydasgulbinas

# Optional  link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: instagram
social_username: megamorphf
author: Dovydas Gulbinas
timezone: Europe/Vilnius

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black


markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  jokes:
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  # - jemoji
  # - jekyll-auto-image


img: "/assets/img/"
git_domain: "https://dovydasgulbinas.github.io"

logo: "/assets/img/edge.png"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

  - scope:
      path: ""
      type: jokes
    values:
      layout: page
